compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.5.3.cjs

packageExtensions:
  "react@*":
    dependencies:
      "@types/react": "19.0.1"
  "react-dom@*":
    dependencies:
      "@types/react-dom": "19.0.2"
